Repository minjune8506/FuzzyAI, pull requests merged in 2022-04, with the labels that each got.

#3 [#1] 답장 오는데 걸리는 시간 소속함수
  function_answer.py
Labels: feature

#4 [#1] function_socialize 함수 맘다니 형식으로 정의
  function_answer.py
  function_distance.py
  function_getDegreesOfMembership.py
  function_socialize.py
Labels: refactor

#6 add new rule of meeting count
  function_count.py
Labels: feature

#8 question
  function_question.py
Labels: feature

#9 [#5]Feat : 소속함수 그래프 구현 (matplotlib)
  graph.py
Labels: feature

#10 한달에 만나는 횟수 수정
  .idea/.gitignore
  .idea/FuzzyAI.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  graph.py
Labels: refactor

#11 사다리꼴 넓이 구하는 메소드 정의 및 룰 생성
  .vscode/launch.json
  function_answer.py
  function_count.py
  function_distance.py
  function_getDegreesOfMembership.py
  function_question.py
  function_socialize.py
  graph.py
  rule_calculate.py
Labels: refactor

#17 쓸데없는 파일 지우고 , 후건부 소속함수 총합 그래프로 표현 및 적분값 계산
  .idea/workspace.xml
  func_socialize.py
  function_answer.py
  function_count.py
  function_distance.py
  function_getDegreesOfMembership.py
  function_question.py
  function_socialize.py
  rule_calculate.py
Labels: feature

#18 Refacoring
  .idea/workspace.xml
  func_socialize.py
  graph.py
  main.py
  rule_calculate.py
Labels: refactor

#19 Fuzzy AI ver1.0
  func_count.py
  rule_calculate.py
Labels: enhancement

#20 Update README.md
  README.md
Labels: documentation

#21 rule_0 추가했어요!
  rule_calculate.py
Labels: refactor

#22 Fix : Fix typo
  graph.py
Labels: refactor
